name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    name: cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js with pnpm
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org/'
          scope: '@teclo'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Bump version and tag release
        id: version
        run: |
          NEW_VERSION=$(pnpm version patch --no-git-tag-version)
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git commit -am "Release $NEW_VERSION [skip ci]"
          git tag "$NEW_VERSION"
          git push origin main --follow-tags
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
