name: cd

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Bump version and tag release
        id: version
        run: |
          NEW_VERSION=$(pnpm version patch --no-git-tag-version)
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git commit -am "Release $NEW_VERSION [skip ci]"
          git tag "$NEW_VERSION"
          git push origin main --follow-tags
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
